### ISSUE TITLE
docker-compose build --pull breaks dependent builds within same compose file

### ISSUE THREAD

**Issue by solsson** [Yolean/build-contract#12]
After 1602ed4 and 078eeea we can no longer run compose files with the following convention:
```yaml
  productionimage:
    build:
      context: ../
    image: registry/yolean/something
  testservice:
    depends_on:
      - httpd-latest
    build:
      # This dockerfile has "FROM registry/yolean/something"
      context: ../modify-for-testing
```

An example such build is https://github.com/Reposoft/docker-svn/blob/master/build-contracts/docker-compose.yml where production image builds have local dependencies.
